many config changes

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,7 +1,21 @@
 #!/bin/bash
 set -e
-task frontend-lint
-task backend-lint
-bash ./scripts/git-secrets-check.sh
+
+task frontend-lint 2>/dev/null
+if [ $? != "0" ]; then
+  echo "Frontend lint failed"
+  exit 1
+fi
+
+task backend-lint 2>/dev/null
+if [ $? != "0" ]; then
+  echo "Backend lint failed"
+  exit 1
+fi
+
+# git-secrets needs to be installed for macos
+#git secrets --pre_commit_hook -- "$@"
+#git secrets --prepare_commit_msg_hook -- "$@"
+#bash ./scripts/git-secrets-check.sh
 branch=$(git symbolic-ref --short HEAD)
 #bash ./scripts/trufflehog-check.sh "$branch"
