Fail job if png not found

diff --git a/.circleci/util/jobs.yml b/.circleci/util/jobs.yml
--- a/.circleci/util/jobs.yml
+++ b/.circleci/util/jobs.yml
@@ -14,5 +14,9 @@
             fi
             docker-compose run --rm web bash -c \
             "./manage.py graph_models -a -g -o tdp_erd.png"
+            if [[ ! -f tdp_erd.png ]]; then
+              echo "Entity Relationship Diagram not found."
+              exit 1
+            fi
       - store_artifacts:
           path: tdrs-backend/tdp_erd.png
